# Generated by Django 5.2.1 on 2025-06-12 16:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the equipment', max_length=100)),
                ('description', models.TextField(help_text='Description of the equipment')),
                ('model_number', models.CharField(blank=True, help_text='Model number of the equipment', max_length=50)),
                ('purchase_date', models.DateField(blank=True, help_text='Date when the equipment was purchased', null=True)),
                ('last_serviced', models.DateField(blank=True, help_text='Date when the equipment was last serviced', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the equipment is currently available for use')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the equipment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this service', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration_minutes', models.PositiveIntegerField(help_text='Typical duration of the service in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, to='studio_services.servicefeature')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['name'],
            },
        ),
    ]
