# Generated by Django 5.2.1 on 2025-06-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_services', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
