# Generated by Django 5.2.1 on 2025-06-28 08:42

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator

class Migration(migrations.Migration):

    dependencies = [
        ('studio_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='session_type',
            field=models.CharField(max_length=10, choices=[('photo', 'Photography'), ('video', 'Videography'), ('both', 'Both')]),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='duration',
            field=models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='status',
            field=models.CharField(max_length=10, choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending'),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
