# Generated by Django 5.2.1 on 2025-06-28 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_booking', '0003_create_availableslot_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='bookingsession',
            options={'verbose_name': 'Booking Session', 'verbose_name_plural': 'Booking Sessions'},
        ),
        migrations.RemoveField(
            model_name='bookingsession',
            name='date',
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='client_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='client_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='client_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='dates',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='bookingsession',
            name='session_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('portrait', 'Portrait'), ('event', 'Event'), ('commercial', 'Commercial')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='availableslot',
            unique_together={('date', 'start_time')},
        ),
    ]
