# Generated by Django 5.2.1 on 2025-06-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_booking', '0004_alter_availableslot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsession',
            name='session_type',
            field=models.CharField(choices=[('wedding', 'Wedding Photography'), ('portrait', 'Portrait Session'), ('family', 'Family Photography'), ('maternity', 'Maternity Session'), ('newborn', 'Newborn Photography'), ('event', 'Event Coverage'), ('commercial', 'Commercial Shoot'), ('other', 'Other')], max_length=20),
        ),
    ]
