# Generated by Django 5.2.1 on 2025-07-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_booking', '0005_update_session_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for the session gallery'),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='testimonial',
            field=models.TextField(blank=True, help_text='Client feedback/testimonial'),
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='testimonial_approved',
            field=models.BooleanField(default=False, help_text='Mark if testimonial is approved for display'),
        ),
    ]
