# Generated by Django 5.2.1 on 2025-07-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_booking', '0007_alter_bookingsession_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableslot',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='availableslot',
            unique_together={('date',)},
        ),
        migrations.RemoveField(
            model_name='bookingsession',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='availableslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availableslot',
            name='start_time',
        ),
    ]
