# Generated by Django 5.2.1 on 2025-06-21 14:58

import django.core.validators
import django.utils.timezone
import testimonials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name="Client's Name")),
                ('client_role', models.CharField(blank=True, help_text='E.g., Bride, CEO, Happy Customer', max_length=100, verbose_name="Client's Role/Title")),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to=testimonials.models.client_photo_path, verbose_name="Client's Photo")),
                ('content', models.TextField(help_text='What the client said about your service', verbose_name='Testimonial Content')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('service_type', models.CharField(choices=[('wedding', 'Wedding Photography'), ('portrait', 'Portrait Session'), ('family', 'Family Session'), ('event', 'Event Coverage'), ('commercial', 'Commercial'), ('other', 'Other')], default='other', max_length=20, verbose_name='Service Type')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this testimonial on the homepage', verbose_name='Featured on Homepage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
