# Generated by Django 5.2.1 on 2025-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's name", max_length=100)),
                ('role', models.CharField(blank=True, help_text="Client's role or occasion (e.g., 'Bride', 'Corporate Client')", max_length=100)),
                ('image', models.ImageField(blank=True, help_text="Client's photo", null=True, upload_to='testimonials/')),
                ('content', models.TextField(help_text='The testimonial text')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Rating from 1 to 5 stars')),
                ('service_type', models.CharField(blank=True, help_text="Type of service received (e.g., 'Wedding Photography', 'Portrait Session')", max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this testimonial on the home page')),
            ],
            options={
                'ordering': ['-date', '-rating'],
            },
        ),
    ]
