# Generated by Django 5.2.1 on 2025-06-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
